//AUTOGENERATED CODE DO NOT EDIT
package interfaces

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/efs"
)

type EFSClient interface {
	DescribeFileSystems(ctx context.Context, params *efs.DescribeFileSystemsInput, optFns ...func(*efs.Options)) (*efs.DescribeFileSystemsOutput, error)
}
