
-- AUTOGENERATED BY VIEW-GENERATOR, DO NOT MODIFY
CREATE OR REPLACE VIEW distinct_ec2_placement_groups AS 
WITH
	filter AS (
	SELECT
		*
	, "max"(report_time) OVER (PARTITION BY group_id) oldest_report_time
	FROM
		ec2_placement_groups
) 
SELECT *
FROM
	filter
WHERE (report_time = oldest_report_time)