//AUTOGENERATED CODE DO NOT EDIT
// This file is automatically generated from /internal/codegen/templates/aws_resource_file.tmpl
package sns

type Subscription struct {
	Endpoint                     string `bson:"endpoint,omitempty" ion:"endpoint" dynamodbav:"endpoint,omitempty" parquet:"name=endpoint,type=BYTE_ARRAY,convertedtype=UTF8" json:"endpoint,omitempty" diff:"endpoint"`
	Owner                        string `bson:"owner,omitempty" ion:"owner" dynamodbav:"owner,omitempty" parquet:"name=owner,type=BYTE_ARRAY,convertedtype=UTF8" json:"owner,omitempty" diff:"owner"`
	Protocol                     string `bson:"protocol,omitempty" ion:"protocol" dynamodbav:"protocol,omitempty" parquet:"name=protocol,type=BYTE_ARRAY,convertedtype=UTF8" json:"protocol,omitempty" diff:"protocol"`
	SubscriptionArn              string `bson:"subscription_arn,omitempty" ion:"subscription_arn" dynamodbav:"subscription_arn,omitempty" parquet:"name=subscription_arn,type=BYTE_ARRAY,convertedtype=UTF8" inventory_primary_key:"true" json:"subscription_arn,omitempty" diff:"subscription_arn,identifier"`
	TopicArn                     string `bson:"topic_arn,omitempty" ion:"topic_arn" dynamodbav:"topic_arn,omitempty" parquet:"name=topic_arn,type=BYTE_ARRAY,convertedtype=UTF8" json:"topic_arn,omitempty" diff:"topic_arn"`
	AccountId                    string `bson:"account_id,omitempty" ion:"account_id" dynamodbav:"account_id,omitempty" parquet:"name=account_id,type=BYTE_ARRAY,convertedtype=UTF8" json:"account_id,omitempty" diff:"account_id"`
	Region                       string `bson:"region,omitempty" ion:"region" dynamodbav:"region,omitempty" parquet:"name=region,type=BYTE_ARRAY,convertedtype=UTF8" json:"region,omitempty" diff:"region"`
	ReportTime                   int64  `bson:"report_time,omitempty" ion:"report_time" dynamodbav:"report_time,omitempty" parquet:"name=report_time,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"report_time,omitempty" diff:"report_time,immutable"`
	InventoryUUID                string `bson:"_id,omitempty" ion:"_id" dynamodbav:"_id,omitempty" parquet:"name=inventory_uuid,type=BYTE_ARRAY,convertedtype=UTF8" json:"_id,omitempty" diff:"-"`
	ConfirmationWasAuthenticated bool   `bson:"confirmation_was_authenticated,omitempty" ion:"confirmation_was_authenticated" dynamodbav:"confirmation_was_authenticated" parquet:"name=confirmation_was_authenticated,type=BOOLEAN" json:"confirmation_was_authenticated,omitempty" diff:"confirmation_was_authenticated"`
	DeliveryPolicy               string `bson:"delivery_policy,omitempty" ion:"delivery_policy" dynamodbav:"delivery_policy,omitempty" parquet:"name=delivery_policy,type=BYTE_ARRAY,convertedtype=UTF8" json:"delivery_policy,omitempty" diff:"delivery_policy"`
	EffectiveDeliveryPolicy      string `bson:"effective_delivery_policy,omitempty" ion:"effective_delivery_policy" dynamodbav:"effective_delivery_policy,omitempty" parquet:"name=effective_delivery_policy,type=BYTE_ARRAY,convertedtype=UTF8" json:"effective_delivery_policy,omitempty" diff:"effective_delivery_policy"`
	FilterPolicy                 string `bson:"filter_policy,omitempty" ion:"filter_policy" dynamodbav:"filter_policy,omitempty" parquet:"name=filter_policy,type=BYTE_ARRAY,convertedtype=UTF8" json:"filter_policy,omitempty" diff:"filter_policy"`
	PendingConfirmation          bool   `bson:"pending_confirmation,omitempty" ion:"pending_confirmation" dynamodbav:"pending_confirmation" parquet:"name=pending_confirmation,type=BOOLEAN" json:"pending_confirmation,omitempty" diff:"pending_confirmation"`
	RawMessageDelivery           bool   `bson:"raw_message_delivery,omitempty" ion:"raw_message_delivery" dynamodbav:"raw_message_delivery" parquet:"name=raw_message_delivery,type=BOOLEAN" json:"raw_message_delivery,omitempty" diff:"raw_message_delivery"`
	RedrivePolicy                string `bson:"redrive_policy,omitempty" ion:"redrive_policy" dynamodbav:"redrive_policy,omitempty" parquet:"name=redrive_policy,type=BYTE_ARRAY,convertedtype=UTF8" json:"redrive_policy,omitempty" diff:"redrive_policy"`
	SubscriptionRoleArn          string `bson:"subscription_role_arn,omitempty" ion:"subscription_role_arn" dynamodbav:"subscription_role_arn,omitempty" parquet:"name=subscription_role_arn,type=BYTE_ARRAY,convertedtype=UTF8" json:"subscription_role_arn,omitempty" diff:"subscription_role_arn"`
}
