
-- AUTOGENERATED BY VIEW-GENERATOR, DO NOT MODIFY
CREATE OR REPLACE VIEW distinct_ecs_clusters AS 
WITH
	filter AS (
	SELECT
		*
	, "max"(report_time) OVER (PARTITION BY cluster_arn) oldest_report_time
	FROM
		ecs_clusters
) 
SELECT *
FROM
	filter
WHERE (report_time = oldest_report_time)