//AUTOGENERATED CODE DO NOT EDIT
package redshift

import (
	"github.com/gin-gonic/gin"
	"github.com/sheacloud/cloud-inventory/internal/api/routes"
)

// GetRedshiftMetadata godoc
// @Summary      Get Redshift Metadata
// @Description  get a list of Redshift metadata
// @Tags         aws redshift
// @Produce      json
// @Security     ApiKeyAuth
// @Success      200  {array}   routes.AwsServiceMetadata
// @Failure      400
// @Router       /metadata/aws/redshift [get]
func GetRedshiftMetadata(c *gin.Context) {
	c.IndentedJSON(200, routes.AwsServiceMetadata{
		Resources: []string{
			"clusters",
		},
	})
}
