//AUTOGENERATED CODE DO NOT EDIT
package elasticloadbalancing

type BackendServerDescription struct {
	InstancePort int32    `bson:"instance_port,omitempty" dynamodbav:"instance_port,omitempty" json:"instance_port,omitempty" diff:"instance_port"`
	PolicyNames  []string `bson:"policy_names,omitempty" dynamodbav:"policy_names,omitempty" json:"policy_names,omitempty" diff:"policy_names"`
}

type HealthCheck struct {
	HealthyThreshold   int32  `bson:"healthy_threshold,omitempty" dynamodbav:"healthy_threshold,omitempty" json:"healthy_threshold,omitempty" diff:"healthy_threshold"`
	Interval           int32  `bson:"interval,omitempty" dynamodbav:"interval,omitempty" json:"interval,omitempty" diff:"interval"`
	Target             string `bson:"target,omitempty" dynamodbav:"target,omitempty" json:"target,omitempty" diff:"target"`
	Timeout            int32  `bson:"timeout,omitempty" dynamodbav:"timeout,omitempty" json:"timeout,omitempty" diff:"timeout"`
	UnhealthyThreshold int32  `bson:"unhealthy_threshold,omitempty" dynamodbav:"unhealthy_threshold,omitempty" json:"unhealthy_threshold,omitempty" diff:"unhealthy_threshold"`
}

type Instance struct {
	InstanceId string `bson:"instance_id,omitempty" dynamodbav:"instance_id,omitempty" json:"instance_id,omitempty" diff:"instance_id"`
}

type ListenerDescription struct {
	Listener    *Listener `bson:"listener,omitempty" dynamodbav:"listener,omitempty" json:"listener,omitempty" diff:"listener"`
	PolicyNames []string  `bson:"policy_names,omitempty" dynamodbav:"policy_names,omitempty" json:"policy_names,omitempty" diff:"policy_names"`
}

type Listener struct {
	InstancePort     int32  `bson:"instance_port,omitempty" dynamodbav:"instance_port,omitempty" json:"instance_port,omitempty" diff:"instance_port"`
	LoadBalancerPort int32  `bson:"load_balancer_port,omitempty" dynamodbav:"load_balancer_port,omitempty" json:"load_balancer_port,omitempty" diff:"load_balancer_port"`
	Protocol         string `bson:"protocol,omitempty" dynamodbav:"protocol,omitempty" json:"protocol,omitempty" diff:"protocol"`
	InstanceProtocol string `bson:"instance_protocol,omitempty" dynamodbav:"instance_protocol,omitempty" json:"instance_protocol,omitempty" diff:"instance_protocol"`
	SSLCertificateId string `bson:"ssl_certificate_id,omitempty" dynamodbav:"ssl_certificate_id,omitempty" json:"ssl_certificate_id,omitempty" diff:"ssl_certificate_id"`
}

type Policies struct {
	AppCookieStickinessPolicies []*AppCookieStickinessPolicy `bson:"app_cookie_stickiness_policies,omitempty" dynamodbav:"app_cookie_stickiness_policies,omitempty" json:"app_cookie_stickiness_policies,omitempty" diff:"app_cookie_stickiness_policies"`
	LBCookieStickinessPolicies  []*LBCookieStickinessPolicy  `bson:"lb_cookie_stickiness_policies,omitempty" dynamodbav:"lb_cookie_stickiness_policies,omitempty" json:"lb_cookie_stickiness_policies,omitempty" diff:"lb_cookie_stickiness_policies"`
	OtherPolicies               []string                     `bson:"other_policies,omitempty" dynamodbav:"other_policies,omitempty" json:"other_policies,omitempty" diff:"other_policies"`
}

type AppCookieStickinessPolicy struct {
	CookieName string `bson:"cookie_name,omitempty" dynamodbav:"cookie_name,omitempty" json:"cookie_name,omitempty" diff:"cookie_name"`
	PolicyName string `bson:"policy_name,omitempty" dynamodbav:"policy_name,omitempty" json:"policy_name,omitempty" diff:"policy_name"`
}

type LBCookieStickinessPolicy struct {
	CookieExpirationPeriod int64  `bson:"cookie_expiration_period,omitempty" dynamodbav:"cookie_expiration_period,omitempty" json:"cookie_expiration_period,omitempty" diff:"cookie_expiration_period"`
	PolicyName             string `bson:"policy_name,omitempty" dynamodbav:"policy_name,omitempty" json:"policy_name,omitempty" diff:"policy_name"`
}

type SourceSecurityGroup struct {
	GroupName  string `bson:"group_name,omitempty" dynamodbav:"group_name,omitempty" json:"group_name,omitempty" diff:"group_name"`
	OwnerAlias string `bson:"owner_alias,omitempty" dynamodbav:"owner_alias,omitempty" json:"owner_alias,omitempty" diff:"owner_alias"`
}
