//AUTOGENERATED CODE DO NOT EDIT
package dynamodb

import (
	"time"
)

type Table struct {
	ArchivalSummary        *ArchivalSummary                   `bson:"archival_summary,omitempty" dynamodbav:"archival_summary,omitempty" json:"archival_summary,omitempty" diff:"archival_summary"`
	AttributeDefinitions   []*AttributeDefinition             `bson:"attribute_definitions,omitempty" dynamodbav:"attribute_definitions,omitempty" json:"attribute_definitions,omitempty" diff:"attribute_definitions"`
	BillingModeSummary     *BillingModeSummary                `bson:"billing_mode_summary,omitempty" dynamodbav:"billing_mode_summary,omitempty" json:"billing_mode_summary,omitempty" diff:"billing_mode_summary"`
	CreationDateTime       *time.Time                         `bson:"creation_date_time,omitempty" dynamodbav:"creation_date_time,unixtime,omitempty" json:"creation_date_time,omitempty" diff:"creation_date_time"`
	GlobalSecondaryIndexes []*GlobalSecondaryIndexDescription `bson:"global_secondary_indexes,omitempty" dynamodbav:"global_secondary_indexes,omitempty" json:"global_secondary_indexes,omitempty" diff:"global_secondary_indexes"`
	GlobalTableVersion     string                             `bson:"global_table_version,omitempty" dynamodbav:"global_table_version,omitempty" json:"global_table_version,omitempty" diff:"global_table_version"`
	ItemCount              int64                              `bson:"item_count,omitempty" dynamodbav:"item_count,omitempty" json:"item_count,omitempty" diff:"item_count"`
	KeySchema              []*KeySchemaElement                `bson:"key_schema,omitempty" dynamodbav:"key_schema,omitempty" json:"key_schema,omitempty" diff:"key_schema"`
	LatestStreamArn        string                             `bson:"latest_stream_arn,omitempty" dynamodbav:"latest_stream_arn,omitempty" json:"latest_stream_arn,omitempty" diff:"latest_stream_arn"`
	LatestStreamLabel      string                             `bson:"latest_stream_label,omitempty" dynamodbav:"latest_stream_label,omitempty" json:"latest_stream_label,omitempty" diff:"latest_stream_label"`
	LocalSecondaryIndexes  []*LocalSecondaryIndexDescription  `bson:"local_secondary_indexes,omitempty" dynamodbav:"local_secondary_indexes,omitempty" json:"local_secondary_indexes,omitempty" diff:"local_secondary_indexes"`
	ProvisionedThroughput  *ProvisionedThroughputDescription  `bson:"provisioned_throughput,omitempty" dynamodbav:"provisioned_throughput,omitempty" json:"provisioned_throughput,omitempty" diff:"provisioned_throughput"`
	Replicas               []*ReplicaDescription              `bson:"replicas,omitempty" dynamodbav:"replicas,omitempty" json:"replicas,omitempty" diff:"replicas"`
	RestoreSummary         *RestoreSummary                    `bson:"restore_summary,omitempty" dynamodbav:"restore_summary,omitempty" json:"restore_summary,omitempty" diff:"restore_summary"`
	SSEDescription         *SSEDescription                    `bson:"sse_description,omitempty" dynamodbav:"sse_description,omitempty" json:"sse_description,omitempty" diff:"sse_description"`
	StreamSpecification    *StreamSpecification               `bson:"stream_specification,omitempty" dynamodbav:"stream_specification,omitempty" json:"stream_specification,omitempty" diff:"stream_specification"`
	TableArn               string                             `bson:"table_arn,omitempty" dynamodbav:"table_arn,omitempty" inventory_primary_key:"true" json:"table_arn,omitempty" diff:"table_arn,identifier"`
	TableClassSummary      *TableClassSummary                 `bson:"table_class_summary,omitempty" dynamodbav:"table_class_summary,omitempty" json:"table_class_summary,omitempty" diff:"table_class_summary"`
	TableId                string                             `bson:"table_id,omitempty" dynamodbav:"table_id,omitempty" json:"table_id,omitempty" diff:"table_id"`
	TableName              string                             `bson:"table_name,omitempty" dynamodbav:"table_name,omitempty" json:"table_name,omitempty" diff:"table_name"`
	TableSizeBytes         int64                              `bson:"table_size_bytes,omitempty" dynamodbav:"table_size_bytes,omitempty" json:"table_size_bytes,omitempty" diff:"table_size_bytes"`
	TableStatus            string                             `bson:"table_status,omitempty" dynamodbav:"table_status,omitempty" json:"table_status,omitempty" diff:"table_status"`
	AccountId              string                             `bson:"account_id,omitempty" dynamodbav:"account_id,omitempty" json:"account_id,omitempty" diff:"account_id"`
	Region                 string                             `bson:"region,omitempty" dynamodbav:"region,omitempty" json:"region,omitempty" diff:"region"`
	ReportTime             time.Time                          `bson:"report_time,omitempty" dynamodbav:"report_time,unixtime,omitempty" json:"report_time,omitempty" diff:"report_time,immutable"`
	InventoryUUID          string                             `bson:"_id,omitempty" dynamodbav:"_id,omitempty" json:"_id,omitempty" diff:"-"`
	Tags                   map[string]string                  `bson:"tags,omitempty" dynamodbav:"tags,omitempty" json:"tags,omitempty" diff:"tags"`
}
