//AUTOGENERATED CODE DO NOT EDIT
package ec2



type DhcpOptions struct {
	DhcpConfigurations []*DhcpConfiguration `parquet:"name=dhcp_configurations,type=MAP,convertedtype=LIST"`
	DhcpOptionsId string `parquet:"name=dhcp_options_id,type=BYTE_ARRAY,convertedtype=UTF8" inventory_primary_key:"true"`
	OwnerId string `parquet:"name=owner_id,type=BYTE_ARRAY,convertedtype=UTF8"`
	TagsOld []*Tag `parquet:"name=tags_old,type=MAP,convertedtype=LIST"`
	AccountId string `parquet:"name=account_id,type=BYTE_ARRAY,convertedtype=UTF8"`
	Region string `parquet:"name=region,type=BYTE_ARRAY,convertedtype=UTF8"`
	ReportTime int64 `parquet:"name=report_time,type=INT64,convertedtype=TIMESTAMP_MILLIS"`
	Tags map[string]string `parquet:"name=tags,type=MAP,keytype=BYTE_ARRAY,valuetype=BYTE_ARRAY,keyconvertedtype=UTF8,valueconvertedtype=UTF8"`
}

