//AUTOGENERATED CODE DO NOT EDIT
package ec2

import (
	"time"
)

type TransitGateway struct {
	CreationTime      *time.Time             `json:"-"`
	Description       string                 `parquet:"name=description,type=BYTE_ARRAY,convertedtype=UTF8" json:"description" diff:"description"`
	Options           *TransitGatewayOptions `parquet:"name=options" json:"options" diff:"options"`
	OwnerId           string                 `parquet:"name=owner_id,type=BYTE_ARRAY,convertedtype=UTF8" json:"owner_id" diff:"owner_id"`
	State             string                 `parquet:"name=state,type=BYTE_ARRAY,convertedtype=UTF8" json:"state" diff:"state"`
	Tags              map[string]string      `parquet:"name=tags,type=MAP,keytype=BYTE_ARRAY,valuetype=BYTE_ARRAY,keyconvertedtype=UTF8,valueconvertedtype=UTF8" json:"tags" diff:"tags"`
	TransitGatewayArn string                 `parquet:"name=transit_gateway_arn,type=BYTE_ARRAY,convertedtype=UTF8" json:"transit_gateway_arn" diff:"transit_gateway_arn"`
	TransitGatewayId  string                 `parquet:"name=transit_gateway_id,type=BYTE_ARRAY,convertedtype=UTF8" inventory_primary_key:"true" json:"transit_gateway_id" diff:"transit_gateway_id,identifier"`
	AccountId         string                 `parquet:"name=account_id,type=BYTE_ARRAY,convertedtype=UTF8" json:"account_id" diff:"account_id"`
	Region            string                 `parquet:"name=region,type=BYTE_ARRAY,convertedtype=UTF8" json:"region" diff:"region"`
	ReportTime        int64                  `parquet:"name=report_time,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"report_time" diff:"report_time,immutable"`
	CreationTimeMilli int64                  `parquet:"name=creation_time,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"creation_time" diff:"creation_time"`
}

func (x *TransitGateway) GetReportTime() int64 {
	return x.ReportTime
}
