//AUTOGENERATED CODE DO NOT EDIT
package ec2

type InstanceTypeInfo struct {
	AutoRecoverySupported         bool                      `parquet:"name=auto_recovery_supported,type=BOOLEAN"`
	BareMetal                     bool                      `parquet:"name=bare_metal,type=BOOLEAN"`
	BurstablePerformanceSupported bool                      `parquet:"name=burstable_performance_supported,type=BOOLEAN"`
	CurrentGeneration             bool                      `parquet:"name=current_generation,type=BOOLEAN"`
	DedicatedHostsSupported       bool                      `parquet:"name=dedicated_hosts_supported,type=BOOLEAN"`
	EbsInfo                       *EbsInfo                  `parquet:"name=ebs_info"`
	FpgaInfo                      *FpgaInfo                 `parquet:"name=fpga_info"`
	FreeTierEligible              bool                      `parquet:"name=free_tier_eligible,type=BOOLEAN"`
	GpuInfo                       *GpuInfo                  `parquet:"name=gpu_info"`
	HibernationSupported          bool                      `parquet:"name=hibernation_supported,type=BOOLEAN"`
	Hypervisor                    string                    `parquet:"name=hypervisor,type=BYTE_ARRAY,convertedtype=UTF8"`
	InferenceAcceleratorInfo      *InferenceAcceleratorInfo `parquet:"name=inference_accelerator_info"`
	InstanceStorageInfo           *InstanceStorageInfo      `parquet:"name=instance_storage_info"`
	InstanceStorageSupported      bool                      `parquet:"name=instance_storage_supported,type=BOOLEAN"`
	InstanceType                  string                    `parquet:"name=instance_type,type=BYTE_ARRAY,convertedtype=UTF8" inventory_primary_key:"true"`
	MemoryInfo                    *MemoryInfo               `parquet:"name=memory_info"`
	NetworkInfo                   *NetworkInfo              `parquet:"name=network_info"`
	PlacementGroupInfo            *PlacementGroupInfo       `parquet:"name=placement_group_info"`
	ProcessorInfo                 *ProcessorInfo            `parquet:"name=processor_info"`
	SupportedBootModes            []string                  `parquet:"name=supported_boot_modes,type=MAP,convertedtype=LIST,valuetype=BYTE_ARRAY,valueconvertedtype=UTF8"`
	SupportedRootDeviceTypes      []string                  `parquet:"name=supported_root_device_types,type=MAP,convertedtype=LIST,valuetype=BYTE_ARRAY,valueconvertedtype=UTF8"`
	SupportedUsageClasses         []string                  `parquet:"name=supported_usage_classes,type=MAP,convertedtype=LIST,valuetype=BYTE_ARRAY,valueconvertedtype=UTF8"`
	SupportedVirtualizationTypes  []string                  `parquet:"name=supported_virtualization_types,type=MAP,convertedtype=LIST,valuetype=BYTE_ARRAY,valueconvertedtype=UTF8"`
	VCpuInfo                      *VCpuInfo                 `parquet:"name=v_cpu_info"`
	AccountId                     string                    `parquet:"name=account_id,type=BYTE_ARRAY,convertedtype=UTF8"`
	Region                        string                    `parquet:"name=region,type=BYTE_ARRAY,convertedtype=UTF8"`
	ReportTime                    int64                     `parquet:"name=report_time,type=INT64,convertedtype=TIMESTAMP_MILLIS"`
}
