//AUTOGENERATED CODE DO NOT EDIT
package ec2

type DhcpOptions struct {
	DhcpConfigurations []*DhcpConfiguration `parquet:"name=dhcp_configurations,type=MAP,convertedtype=LIST" json:"dhcp_configurations" diff:"dhcp_configurations"`
	DhcpOptionsId      string               `parquet:"name=dhcp_options_id,type=BYTE_ARRAY,convertedtype=UTF8" inventory_primary_key:"true" json:"dhcp_options_id" diff:"dhcp_options_id,identifier"`
	OwnerId            string               `parquet:"name=owner_id,type=BYTE_ARRAY,convertedtype=UTF8" json:"owner_id" diff:"owner_id"`
	Tags               map[string]string    `parquet:"name=tags,type=MAP,keytype=BYTE_ARRAY,valuetype=BYTE_ARRAY,keyconvertedtype=UTF8,valueconvertedtype=UTF8" json:"tags" diff:"tags"`
	AccountId          string               `parquet:"name=account_id,type=BYTE_ARRAY,convertedtype=UTF8" json:"account_id" diff:"account_id"`
	Region             string               `parquet:"name=region,type=BYTE_ARRAY,convertedtype=UTF8" json:"region" diff:"region"`
	ReportTime         int64                `parquet:"name=report_time,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"report_time" diff:"report_time,immutable"`
}

func (x *DhcpOptions) GetReportTime() int64 {
	return x.ReportTime
}
