//AUTOGENERATED CODE DO NOT EDIT
package dynamodb

import (
	"time"
)

type TableDescription struct {
	ArchivalSummary *ArchivalSummary `parquet:"name=archival_summary"`
	AttributeDefinitions []*AttributeDefinition `parquet:"name=attribute_definitions,type=MAP,convertedtype=LIST"`
	BillingModeSummary *BillingModeSummary `parquet:"name=billing_mode_summary"`
	CreationDateTime *time.Time 
	GlobalSecondaryIndexes []*GlobalSecondaryIndexDescription `parquet:"name=global_secondary_indexes,type=MAP,convertedtype=LIST"`
	GlobalTableVersion string `parquet:"name=global_table_version,type=BYTE_ARRAY,convertedtype=UTF8"`
	ItemCount int64 `parquet:"name=item_count,type=INT64"`
	KeySchema []*KeySchemaElement `parquet:"name=key_schema,type=MAP,convertedtype=LIST"`
	LatestStreamArn string `parquet:"name=latest_stream_arn,type=BYTE_ARRAY,convertedtype=UTF8"`
	LatestStreamLabel string `parquet:"name=latest_stream_label,type=BYTE_ARRAY,convertedtype=UTF8"`
	LocalSecondaryIndexes []*LocalSecondaryIndexDescription `parquet:"name=local_secondary_indexes,type=MAP,convertedtype=LIST"`
	ProvisionedThroughput *ProvisionedThroughputDescription `parquet:"name=provisioned_throughput"`
	Replicas []*ReplicaDescription `parquet:"name=replicas,type=MAP,convertedtype=LIST"`
	RestoreSummary *RestoreSummary `parquet:"name=restore_summary"`
	SSEDescription *SSEDescription `parquet:"name=sse_description"`
	StreamSpecification *StreamSpecification `parquet:"name=stream_specification"`
	TableArn string `parquet:"name=table_arn,type=BYTE_ARRAY,convertedtype=UTF8" inventory_primary_key:"true"`
	TableClassSummary *TableClassSummary `parquet:"name=table_class_summary"`
	TableId string `parquet:"name=table_id,type=BYTE_ARRAY,convertedtype=UTF8"`
	TableName string `parquet:"name=table_name,type=BYTE_ARRAY,convertedtype=UTF8"`
	TableSizeBytes int64 `parquet:"name=table_size_bytes,type=INT64"`
	TableStatus string `parquet:"name=table_status,type=BYTE_ARRAY,convertedtype=UTF8"`
	AccountId string `parquet:"name=account_id,type=BYTE_ARRAY,convertedtype=UTF8"`
	Region string `parquet:"name=region,type=BYTE_ARRAY,convertedtype=UTF8"`
	ReportTime int64 `parquet:"name=report_time,type=INT64,convertedtype=TIMESTAMP_MILLIS"`
	Tags map[string]string `parquet:"name=tags,type=MAP,keytype=BYTE_ARRAY,valuetype=BYTE_ARRAY,keyconvertedtype=UTF8,valueconvertedtype=UTF8"`
	CreationDateTimeMilli int64 `parquet:"name=creation_date_time,type=INT64,convertedtype=TIMESTAMP_MILLIS"`
}

