//AUTOGENERATED CODE DO NOT EDIT
package apigateway

import (
	"time"
)

type RestApi struct {
	ApiKeySource              string                 `bson:"api_key_source,omitempty" dynamodbav:"api_key_source,omitempty" json:"api_key_source,omitempty" diff:"api_key_source"`
	BinaryMediaTypes          []string               `bson:"binary_media_types,omitempty" dynamodbav:"binary_media_types,omitempty" json:"binary_media_types,omitempty" diff:"binary_media_types"`
	CreatedDate               *time.Time             `bson:"created_date,omitempty" dynamodbav:"created_date,unixtime,omitempty" json:"created_date,omitempty" diff:"created_date"`
	Description               string                 `bson:"description,omitempty" dynamodbav:"description,omitempty" json:"description,omitempty" diff:"description"`
	DisableExecuteApiEndpoint bool                   `bson:"disable_execute_api_endpoint,omitempty" dynamodbav:"disable_execute_api_endpoint" json:"disable_execute_api_endpoint,omitempty" diff:"disable_execute_api_endpoint"`
	EndpointConfiguration     *EndpointConfiguration `bson:"endpoint_configuration,omitempty" dynamodbav:"endpoint_configuration,omitempty" json:"endpoint_configuration,omitempty" diff:"endpoint_configuration"`
	Id                        string                 `bson:"id,omitempty" dynamodbav:"id,omitempty" inventory_primary_key:"true" json:"id,omitempty" diff:"id,identifier"`
	MinimumCompressionSize    int32                  `bson:"minimum_compression_size,omitempty" dynamodbav:"minimum_compression_size,omitempty" json:"minimum_compression_size,omitempty" diff:"minimum_compression_size"`
	Name                      string                 `bson:"name,omitempty" dynamodbav:"name,omitempty" json:"name,omitempty" diff:"name"`
	Policy                    string                 `bson:"policy,omitempty" dynamodbav:"policy,omitempty" json:"policy,omitempty" diff:"policy"`
	Tags                      map[string]string      `bson:"tags,omitempty" dynamodbav:"tags,omitempty" json:"tags,omitempty" diff:"tags"`
	Version                   string                 `bson:"version,omitempty" dynamodbav:"version,omitempty" json:"version,omitempty" diff:"version"`
	Warnings                  []string               `bson:"warnings,omitempty" dynamodbav:"warnings,omitempty" json:"warnings,omitempty" diff:"warnings"`
	AccountId                 string                 `bson:"account_id,omitempty" dynamodbav:"account_id,omitempty" json:"account_id,omitempty" diff:"account_id"`
	Region                    string                 `bson:"region,omitempty" dynamodbav:"region,omitempty" json:"region,omitempty" diff:"region"`
	ReportTime                time.Time              `bson:"report_time,omitempty" dynamodbav:"report_time,unixtime,omitempty" json:"report_time,omitempty" diff:"report_time,immutable"`
	InventoryUUID             string                 `bson:"_id,omitempty" dynamodbav:"_id,omitempty" json:"_id,omitempty" diff:"-"`
	Stages                    []*Stage               `bson:"stages,omitempty" dynamodbav:"stages,omitempty" json:"stages,omitempty" diff:"stages"`
	Resources                 []*Resource            `bson:"resources,omitempty" dynamodbav:"resources,omitempty" json:"resources,omitempty" diff:"resources"`
}
