//AUTOGENERATED CODE DO NOT EDIT
// This file is automatically generated from /internal/codegen/templates/aws_referenced_resource_file.tmpl
package iam

type AttachedPolicy struct {
	PolicyArn  string `bson:"policy_arn,omitempty" ion:"policy_arn" dynamodbav:"policy_arn,omitempty" parquet:"name=policy_arn,type=BYTE_ARRAY,convertedtype=UTF8" json:"policy_arn,omitempty" diff:"policy_arn"`
	PolicyName string `bson:"policy_name,omitempty" ion:"policy_name" dynamodbav:"policy_name,omitempty" parquet:"name=policy_name,type=BYTE_ARRAY,convertedtype=UTF8" json:"policy_name,omitempty" diff:"policy_name"`
}

type Tag struct {
	Key   string `bson:"key,omitempty" ion:"key" dynamodbav:"key,omitempty" parquet:"name=key,type=BYTE_ARRAY,convertedtype=UTF8" json:"key,omitempty" diff:"key"`
	Value string `bson:"value,omitempty" ion:"value" dynamodbav:"value,omitempty" parquet:"name=value,type=BYTE_ARRAY,convertedtype=UTF8" json:"value,omitempty" diff:"value"`
}

type AttachedPermissionsBoundary struct {
	PermissionsBoundaryArn  string `bson:"permissions_boundary_arn,omitempty" ion:"permissions_boundary_arn" dynamodbav:"permissions_boundary_arn,omitempty" parquet:"name=permissions_boundary_arn,type=BYTE_ARRAY,convertedtype=UTF8" json:"permissions_boundary_arn,omitempty" diff:"permissions_boundary_arn"`
	PermissionsBoundaryType string `bson:"permissions_boundary_type,omitempty" ion:"permissions_boundary_type" dynamodbav:"permissions_boundary_type,omitempty" parquet:"name=permissions_boundary_type,type=BYTE_ARRAY,convertedtype=UTF8" json:"permissions_boundary_type,omitempty" diff:"permissions_boundary_type"`
}

type RoleLastUsed struct {
	LastUsedDate int64  `bson:"last_used_date,omitempty" ion:"last_used_date" dynamodbav:"last_used_date,omitempty" parquet:"name=last_used_date,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"last_used_date,omitempty" diff:"last_used_date"`
	Region       string `bson:"region,omitempty" ion:"region" dynamodbav:"region,omitempty" parquet:"name=region,type=BYTE_ARRAY,convertedtype=UTF8" json:"region,omitempty" diff:"region"`
}

type AccessKeyMetadata struct {
	AccessKeyId string `bson:"access_key_id,omitempty" ion:"access_key_id" dynamodbav:"access_key_id,omitempty" parquet:"name=access_key_id,type=BYTE_ARRAY,convertedtype=UTF8" json:"access_key_id,omitempty" diff:"access_key_id"`
	CreateDate  int64  `bson:"create_date,omitempty" ion:"create_date" dynamodbav:"create_date,omitempty" parquet:"name=create_date,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"create_date,omitempty" diff:"create_date"`
	Status      string `bson:"status,omitempty" ion:"status" dynamodbav:"status,omitempty" parquet:"name=status,type=BYTE_ARRAY,convertedtype=UTF8" json:"status,omitempty" diff:"status"`
}

type LoginProfile struct {
	CreateDate            int64 `bson:"create_date,omitempty" ion:"create_date" dynamodbav:"create_date,omitempty" parquet:"name=create_date,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"create_date,omitempty" diff:"create_date"`
	PasswordResetRequired bool  `bson:"password_reset_required,omitempty" ion:"password_reset_required" dynamodbav:"password_reset_required" parquet:"name=password_reset_required,type=BOOLEAN" json:"password_reset_required,omitempty" diff:"password_reset_required"`
}
