//AUTOGENERATED CODE DO NOT EDIT
package iam

import (
	"time"
)

type Group struct {
	Arn              string            `bson:"arn,omitempty" dynamodbav:"arn,omitempty" json:"arn,omitempty" diff:"arn"`
	CreateDate       *time.Time        `bson:"create_date,omitempty" dynamodbav:"create_date,unixtime,omitempty" json:"create_date,omitempty" diff:"create_date"`
	GroupId          string            `bson:"group_id,omitempty" dynamodbav:"group_id,omitempty" inventory_primary_key:"true" json:"group_id,omitempty" diff:"group_id,identifier"`
	GroupName        string            `bson:"group_name,omitempty" dynamodbav:"group_name,omitempty" json:"group_name,omitempty" diff:"group_name"`
	Path             string            `bson:"path,omitempty" dynamodbav:"path,omitempty" json:"path,omitempty" diff:"path"`
	AccountId        string            `bson:"account_id,omitempty" dynamodbav:"account_id,omitempty" json:"account_id,omitempty" diff:"account_id"`
	Region           string            `bson:"region,omitempty" dynamodbav:"region,omitempty" json:"region,omitempty" diff:"region"`
	ReportTime       time.Time         `bson:"report_time,omitempty" dynamodbav:"report_time,unixtime,omitempty" json:"report_time,omitempty" diff:"report_time,immutable"`
	InventoryUUID    string            `bson:"_id,omitempty" dynamodbav:"_id,omitempty" json:"_id,omitempty" diff:"-"`
	InlinePolicies   []string          `bson:"inline_policies,omitempty" dynamodbav:"inline_policies,omitempty" json:"inline_policies,omitempty" diff:"inline_policies"`
	UserIds          []string          `bson:"user_ids,omitempty" dynamodbav:"user_ids,omitempty" json:"user_ids,omitempty" diff:"user_ids"`
	AttachedPolicies []*AttachedPolicy `bson:"attached_policies,omitempty" dynamodbav:"attached_policies,omitempty" json:"attached_policies,omitempty" diff:"attached_policies"`
}
