//AUTOGENERATED CODE DO NOT EDIT
// This file is automatically generated from /internal/codegen/templates/aws_referenced_resource_file.tmpl
package route53

type HostedZoneConfig struct {
	Comment     string `bson:"comment,omitempty" ion:"comment" dynamodbav:"comment,omitempty" parquet:"name=comment,type=BYTE_ARRAY,convertedtype=UTF8" json:"comment,omitempty" diff:"comment"`
	PrivateZone bool   `bson:"private_zone,omitempty" ion:"private_zone" dynamodbav:"private_zone" parquet:"name=private_zone,type=BOOLEAN" json:"private_zone,omitempty" diff:"private_zone"`
}

type LinkedService struct {
	Description      string `bson:"description,omitempty" ion:"description" dynamodbav:"description,omitempty" parquet:"name=description,type=BYTE_ARRAY,convertedtype=UTF8" json:"description,omitempty" diff:"description"`
	ServicePrincipal string `bson:"service_principal,omitempty" ion:"service_principal" dynamodbav:"service_principal,omitempty" parquet:"name=service_principal,type=BYTE_ARRAY,convertedtype=UTF8" json:"service_principal,omitempty" diff:"service_principal"`
}

type VPC struct {
	VPCId     string `bson:"vpc_id,omitempty" ion:"vpc_id" dynamodbav:"vpc_id,omitempty" parquet:"name=vpc_id,type=BYTE_ARRAY,convertedtype=UTF8" json:"vpc_id,omitempty" diff:"vpc_id"`
	VPCRegion string `bson:"vpc_region,omitempty" ion:"vpc_region" dynamodbav:"vpc_region,omitempty" parquet:"name=vpc_region,type=BYTE_ARRAY,convertedtype=UTF8" json:"vpc_region,omitempty" diff:"vpc_region"`
}
