//AUTOGENERATED CODE DO NOT EDIT
package ecs

import (
	"time"
)

type Cluster struct {
	ActiveServicesCount               int32                           `bson:"active_services_count,omitempty" dynamodbav:"active_services_count,omitempty" json:"active_services_count,omitempty" diff:"active_services_count"`
	Attachments                       []*Attachment                   `bson:"attachments,omitempty" dynamodbav:"attachments,omitempty" json:"attachments,omitempty" diff:"attachments"`
	AttachmentsStatus                 string                          `bson:"attachments_status,omitempty" dynamodbav:"attachments_status,omitempty" json:"attachments_status,omitempty" diff:"attachments_status"`
	CapacityProviders                 []string                        `bson:"capacity_providers,omitempty" dynamodbav:"capacity_providers,omitempty" json:"capacity_providers,omitempty" diff:"capacity_providers"`
	ClusterArn                        string                          `bson:"cluster_arn,omitempty" dynamodbav:"cluster_arn,omitempty" inventory_primary_key:"true" json:"cluster_arn,omitempty" diff:"cluster_arn,identifier"`
	ClusterName                       string                          `bson:"cluster_name,omitempty" dynamodbav:"cluster_name,omitempty" json:"cluster_name,omitempty" diff:"cluster_name"`
	Configuration                     *ClusterConfiguration           `bson:"configuration,omitempty" dynamodbav:"configuration,omitempty" json:"configuration,omitempty" diff:"configuration"`
	DefaultCapacityProviderStrategy   []*CapacityProviderStrategyItem `bson:"default_capacity_provider_strategy,omitempty" dynamodbav:"default_capacity_provider_strategy,omitempty" json:"default_capacity_provider_strategy,omitempty" diff:"default_capacity_provider_strategy"`
	PendingTasksCount                 int32                           `bson:"pending_tasks_count,omitempty" dynamodbav:"pending_tasks_count,omitempty" json:"pending_tasks_count,omitempty" diff:"pending_tasks_count"`
	RegisteredContainerInstancesCount int32                           `bson:"registered_container_instances_count,omitempty" dynamodbav:"registered_container_instances_count,omitempty" json:"registered_container_instances_count,omitempty" diff:"registered_container_instances_count"`
	RunningTasksCount                 int32                           `bson:"running_tasks_count,omitempty" dynamodbav:"running_tasks_count,omitempty" json:"running_tasks_count,omitempty" diff:"running_tasks_count"`
	Settings                          []*ClusterSetting               `bson:"settings,omitempty" dynamodbav:"settings,omitempty" json:"settings,omitempty" diff:"settings"`
	Statistics                        []*KeyValuePair                 `bson:"statistics,omitempty" dynamodbav:"statistics,omitempty" json:"statistics,omitempty" diff:"statistics"`
	Status                            string                          `bson:"status,omitempty" dynamodbav:"status,omitempty" json:"status,omitempty" diff:"status"`
	Tags                              map[string]string               `bson:"tags,omitempty" dynamodbav:"tags,omitempty" json:"tags,omitempty" diff:"tags"`
	AccountId                         string                          `bson:"account_id,omitempty" dynamodbav:"account_id,omitempty" json:"account_id,omitempty" diff:"account_id"`
	Region                            string                          `bson:"region,omitempty" dynamodbav:"region,omitempty" json:"region,omitempty" diff:"region"`
	ReportTime                        time.Time                       `bson:"report_time,omitempty" dynamodbav:"report_time,unixtime,omitempty" json:"report_time,omitempty" diff:"report_time,immutable"`
	InventoryUUID                     string                          `bson:"_id,omitempty" dynamodbav:"_id,omitempty" json:"_id,omitempty" diff:"-"`
}
