//AUTOGENERATED CODE DO NOT EDIT
package iam

import (
	"time"
)

type InstanceProfile struct {
	Arn                 string `parquet:"name=arn,type=BYTE_ARRAY,convertedtype=UTF8"`
	CreateDate          *time.Time
	InstanceProfileId   string            `parquet:"name=instance_profile_id,type=BYTE_ARRAY,convertedtype=UTF8" inventory_primary_key:"true"`
	InstanceProfileName string            `parquet:"name=instance_profile_name,type=BYTE_ARRAY,convertedtype=UTF8"`
	Path                string            `parquet:"name=path,type=BYTE_ARRAY,convertedtype=UTF8"`
	Roles               []*Role           `parquet:"name=roles,type=MAP,convertedtype=LIST"`
	TagsOld             []*Tag            `parquet:"name=tags_old,type=MAP,convertedtype=LIST"`
	AccountId           string            `parquet:"name=account_id,type=BYTE_ARRAY,convertedtype=UTF8"`
	Region              string            `parquet:"name=region,type=BYTE_ARRAY,convertedtype=UTF8"`
	ReportTime          int64             `parquet:"name=report_time,type=INT64,convertedtype=TIMESTAMP_MILLIS"`
	CreateDateMilli     int64             `parquet:"name=create_date,type=INT64,convertedtype=TIMESTAMP_MILLIS"`
	Tags                map[string]string `parquet:"name=tags,type=MAP,keytype=BYTE_ARRAY,valuetype=BYTE_ARRAY,keyconvertedtype=UTF8,valueconvertedtype=UTF8"`
}
