//AUTOGENERATED CODE DO NOT EDIT
package iam

import (
	"time"
)

type Group struct {
	Arn              string            `parquet:"name=arn,type=BYTE_ARRAY,convertedtype=UTF8" json:"arn" diff:"arn"`
	CreateDate       *time.Time        `json:"-"`
	GroupId          string            `parquet:"name=group_id,type=BYTE_ARRAY,convertedtype=UTF8" inventory_primary_key:"true" json:"group_id" diff:"group_id,identifier"`
	GroupName        string            `parquet:"name=group_name,type=BYTE_ARRAY,convertedtype=UTF8" json:"group_name" diff:"group_name"`
	Path             string            `parquet:"name=path,type=BYTE_ARRAY,convertedtype=UTF8" json:"path" diff:"path"`
	AccountId        string            `parquet:"name=account_id,type=BYTE_ARRAY,convertedtype=UTF8" json:"account_id" diff:"account_id"`
	Region           string            `parquet:"name=region,type=BYTE_ARRAY,convertedtype=UTF8" json:"region" diff:"region"`
	ReportTime       int64             `parquet:"name=report_time,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"report_time" diff:"report_time,immutable"`
	InlinePolicies   []string          `parquet:"name=inline_policies,type=MAP,convertedtype=LIST,valuetype=BYTE_ARRAY,valueconvertedtype=UTF8" json:"inline_policies" diff:"inline_policies"`
	UserIds          []string          `parquet:"name=user_ids,type=MAP,convertedtype=LIST,valuetype=BYTE_ARRAY,valueconvertedtype=UTF8" json:"user_ids" diff:"user_ids"`
	AttachedPolicies []*AttachedPolicy `parquet:"name=attached_policies,type=MAP,convertedtype=LIST" json:"attached_policies" diff:"attached_policies"`
	CreateDateMilli  int64             `parquet:"name=create_date,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"create_date" diff:"create_date"`
}

func (x *Group) GetReportTime() int64 {
	return x.ReportTime
}
