//AUTOGENERATED CODE DO NOT EDIT
package iam

import (
	"time"
)

type Role struct {
	Arn                 string `parquet:"name=arn,type=BYTE_ARRAY,convertedtype=UTF8" json:"arn" diff:"arn"`
	CreateDate          *time.Time
	Path                string                       `parquet:"name=path,type=BYTE_ARRAY,convertedtype=UTF8" json:"path" diff:"path"`
	RoleId              string                       `parquet:"name=role_id,type=BYTE_ARRAY,convertedtype=UTF8" inventory_primary_key:"true" json:"role_id" diff:"role_id,identifier"`
	RoleName            string                       `parquet:"name=role_name,type=BYTE_ARRAY,convertedtype=UTF8" json:"role_name" diff:"role_name"`
	Description         string                       `parquet:"name=description,type=BYTE_ARRAY,convertedtype=UTF8" json:"description" diff:"description"`
	MaxSessionDuration  int32                        `parquet:"name=max_session_duration,type=INT32" json:"max_session_duration" diff:"max_session_duration"`
	PermissionsBoundary *AttachedPermissionsBoundary `parquet:"name=permissions_boundary" json:"permissions_boundary" diff:"permissions_boundary"`
	RoleLastUsed        *RoleLastUsed                `parquet:"name=role_last_used" json:"role_last_used" diff:"role_last_used"`
	Tags                map[string]string            `parquet:"name=tags,type=MAP,keytype=BYTE_ARRAY,valuetype=BYTE_ARRAY,keyconvertedtype=UTF8,valueconvertedtype=UTF8" json:"tags" diff:"tags"`
	AccountId           string                       `parquet:"name=account_id,type=BYTE_ARRAY,convertedtype=UTF8" json:"account_id" diff:"account_id"`
	Region              string                       `parquet:"name=region,type=BYTE_ARRAY,convertedtype=UTF8" json:"region" diff:"region"`
	ReportTime          int64                        `parquet:"name=report_time,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"report_time" diff:"report_time,immutable"`
	InlinePolicies      []string                     `parquet:"name=inline_policies,type=MAP,convertedtype=LIST,valuetype=BYTE_ARRAY,valueconvertedtype=UTF8" json:"inline_policies" diff:"inline_policies"`
	AttachedPolicies    []*AttachedPolicy            `parquet:"name=attached_policies,type=MAP,convertedtype=LIST" json:"attached_policies" diff:"attached_policies"`
	CreateDateMilli     int64                        `parquet:"name=create_date,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"create_date" diff:"create_date"`
}

func (x *Role) GetReportTime() int64 {
	return x.ReportTime
}
