//AUTOGENERATED CODE DO NOT EDIT
package ec2

import (
	"time"
)

type Address struct {
	AllocationId            string            `bson:"allocation_id,omitempty" dynamodbav:"allocation_id,omitempty" inventory_primary_key:"true" json:"allocation_id,omitempty" diff:"allocation_id,identifier"`
	AssociationId           string            `bson:"association_id,omitempty" dynamodbav:"association_id,omitempty" json:"association_id,omitempty" diff:"association_id"`
	CarrierIp               string            `bson:"carrier_ip,omitempty" dynamodbav:"carrier_ip,omitempty" json:"carrier_ip,omitempty" diff:"carrier_ip"`
	CustomerOwnedIp         string            `bson:"customer_owned_ip,omitempty" dynamodbav:"customer_owned_ip,omitempty" json:"customer_owned_ip,omitempty" diff:"customer_owned_ip"`
	CustomerOwnedIpv4Pool   string            `bson:"customer_owned_ipv4_pool,omitempty" dynamodbav:"customer_owned_ipv4_pool,omitempty" json:"customer_owned_ipv4_pool,omitempty" diff:"customer_owned_ipv4_pool"`
	Domain                  string            `bson:"domain,omitempty" dynamodbav:"domain,omitempty" json:"domain,omitempty" diff:"domain"`
	InstanceId              string            `bson:"instance_id,omitempty" dynamodbav:"instance_id,omitempty" json:"instance_id,omitempty" diff:"instance_id"`
	NetworkBorderGroup      string            `bson:"network_border_group,omitempty" dynamodbav:"network_border_group,omitempty" json:"network_border_group,omitempty" diff:"network_border_group"`
	NetworkInterfaceId      string            `bson:"network_interface_id,omitempty" dynamodbav:"network_interface_id,omitempty" json:"network_interface_id,omitempty" diff:"network_interface_id"`
	NetworkInterfaceOwnerId string            `bson:"network_interface_owner_id,omitempty" dynamodbav:"network_interface_owner_id,omitempty" json:"network_interface_owner_id,omitempty" diff:"network_interface_owner_id"`
	PrivateIpAddress        string            `bson:"private_ip_address,omitempty" dynamodbav:"private_ip_address,omitempty" json:"private_ip_address,omitempty" diff:"private_ip_address"`
	PublicIp                string            `bson:"public_ip,omitempty" dynamodbav:"public_ip,omitempty" json:"public_ip,omitempty" diff:"public_ip"`
	PublicIpv4Pool          string            `bson:"public_ipv4_pool,omitempty" dynamodbav:"public_ipv4_pool,omitempty" json:"public_ipv4_pool,omitempty" diff:"public_ipv4_pool"`
	Tags                    map[string]string `bson:"tags,omitempty" dynamodbav:"tags,omitempty" json:"tags,omitempty" diff:"tags"`
	AccountId               string            `bson:"account_id,omitempty" dynamodbav:"account_id,omitempty" json:"account_id,omitempty" diff:"account_id"`
	Region                  string            `bson:"region,omitempty" dynamodbav:"region,omitempty" json:"region,omitempty" diff:"region"`
	ReportTime              time.Time         `bson:"report_time,omitempty" dynamodbav:"report_time,unixtime,omitempty" json:"report_time,omitempty" diff:"report_time,immutable"`
	InventoryUUID           string            `bson:"_id,omitempty" dynamodbav:"_id,omitempty" json:"_id,omitempty" diff:"-"`
}
