//AUTOGENERATED CODE DO NOT EDIT
package ec2

import (
	"time"
)

type ManagedPrefixList struct {
	AddressFamily  string            `bson:"address_family,omitempty" dynamodbav:"address_family,omitempty" json:"address_family,omitempty" diff:"address_family"`
	MaxEntries     int32             `bson:"max_entries,omitempty" dynamodbav:"max_entries,omitempty" json:"max_entries,omitempty" diff:"max_entries"`
	OwnerId        string            `bson:"owner_id,omitempty" dynamodbav:"owner_id,omitempty" json:"owner_id,omitempty" diff:"owner_id"`
	PrefixListArn  string            `bson:"prefix_list_arn,omitempty" dynamodbav:"prefix_list_arn,omitempty" inventory_primary_key:"true" json:"prefix_list_arn,omitempty" diff:"prefix_list_arn,identifier"`
	PrefixListId   string            `bson:"prefix_list_id,omitempty" dynamodbav:"prefix_list_id,omitempty" json:"prefix_list_id,omitempty" diff:"prefix_list_id"`
	PrefixListName string            `bson:"prefix_list_name,omitempty" dynamodbav:"prefix_list_name,omitempty" json:"prefix_list_name,omitempty" diff:"prefix_list_name"`
	State          string            `bson:"state,omitempty" dynamodbav:"state,omitempty" json:"state,omitempty" diff:"state"`
	StateMessage   string            `bson:"state_message,omitempty" dynamodbav:"state_message,omitempty" json:"state_message,omitempty" diff:"state_message"`
	Tags           map[string]string `bson:"tags,omitempty" dynamodbav:"tags,omitempty" json:"tags,omitempty" diff:"tags"`
	Version        int64             `bson:"version,omitempty" dynamodbav:"version,omitempty" json:"version,omitempty" diff:"version"`
	AccountId      string            `bson:"account_id,omitempty" dynamodbav:"account_id,omitempty" json:"account_id,omitempty" diff:"account_id"`
	Region         string            `bson:"region,omitempty" dynamodbav:"region,omitempty" json:"region,omitempty" diff:"region"`
	ReportTime     time.Time         `bson:"report_time,omitempty" dynamodbav:"report_time,unixtime,omitempty" json:"report_time,omitempty" diff:"report_time,immutable"`
	InventoryUUID  string            `bson:"_id,omitempty" dynamodbav:"_id,omitempty" json:"_id,omitempty" diff:"-"`
}
