//AUTOGENERATED CODE DO NOT EDIT
package awscloud

import (
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	"github.com/aws/aws-sdk-go-v2/service/ec2"
	"github.com/aws/aws-sdk-go-v2/service/s3"

	"github.com/sheacloud/cloud-inventory/pkg/awscloud/interfaces"
)

type AwsClient struct {
	cloudwatchlogsClient *cloudwatchlogs.Client
	ec2Client            *ec2.Client
	s3Client             *s3.Client
}

func NewAwsClient(cfg aws.Config) *AwsClient {
	return &AwsClient{
		cloudwatchlogsClient: cloudwatchlogs.NewFromConfig(cfg),
		ec2Client:            ec2.NewFromConfig(cfg),
		s3Client:             s3.NewFromConfig(cfg),
	}
}

func (c *AwsClient) CloudWatchLogs() interfaces.CloudWatchLogsClient {
	return c.cloudwatchlogsClient
}
func (c *AwsClient) EC2() interfaces.EC2Client {
	return c.ec2Client
}
func (c *AwsClient) S3() interfaces.S3Client {
	return c.s3Client
}
