
-- AUTOGENERATED BY VIEW-GENERATOR, DO NOT MODIFY
CREATE OR REPLACE VIEW daily_distinct_s3_buckets AS 
WITH
	filter AS (
	SELECT
		*
	, "max"(report_time) OVER (PARTITION BY name, report_date) oldest_report_time
	FROM
		s3_buckets
) 
SELECT *
FROM
	filter
WHERE (report_time = oldest_report_time)