//AUTOGENERATED CODE DO NOT EDIT
// This file is automatically generated from /internal/codegen/templates/aws_resource_file.tmpl
package secretsmanager

type Secret struct {
	ARN                    string              `bson:"arn,omitempty" ion:"arn" dynamodbav:"arn,omitempty" parquet:"name=arn,type=BYTE_ARRAY,convertedtype=UTF8" inventory_primary_key:"true" json:"arn,omitempty" diff:"arn,identifier"`
	CreatedDate            int64               `bson:"created_date,omitempty" ion:"created_date" dynamodbav:"created_date,omitempty" parquet:"name=created_date,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"created_date,omitempty" diff:"created_date"`
	DeletedDate            int64               `bson:"deleted_date,omitempty" ion:"deleted_date" dynamodbav:"deleted_date,omitempty" parquet:"name=deleted_date,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"deleted_date,omitempty" diff:"deleted_date"`
	Description            string              `bson:"description,omitempty" ion:"description" dynamodbav:"description,omitempty" parquet:"name=description,type=BYTE_ARRAY,convertedtype=UTF8" json:"description,omitempty" diff:"description"`
	KmsKeyId               string              `bson:"kms_key_id,omitempty" ion:"kms_key_id" dynamodbav:"kms_key_id,omitempty" parquet:"name=kms_key_id,type=BYTE_ARRAY,convertedtype=UTF8" json:"kms_key_id,omitempty" diff:"kms_key_id"`
	LastAccessedDate       int64               `bson:"last_accessed_date,omitempty" ion:"last_accessed_date" dynamodbav:"last_accessed_date,omitempty" parquet:"name=last_accessed_date,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"last_accessed_date,omitempty" diff:"last_accessed_date"`
	LastChangedDate        int64               `bson:"last_changed_date,omitempty" ion:"last_changed_date" dynamodbav:"last_changed_date,omitempty" parquet:"name=last_changed_date,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"last_changed_date,omitempty" diff:"last_changed_date"`
	LastRotatedDate        int64               `bson:"last_rotated_date,omitempty" ion:"last_rotated_date" dynamodbav:"last_rotated_date,omitempty" parquet:"name=last_rotated_date,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"last_rotated_date,omitempty" diff:"last_rotated_date"`
	Name                   string              `bson:"name,omitempty" ion:"name" dynamodbav:"name,omitempty" parquet:"name=name,type=BYTE_ARRAY,convertedtype=UTF8" json:"name,omitempty" diff:"name"`
	OwningService          string              `bson:"owning_service,omitempty" ion:"owning_service" dynamodbav:"owning_service,omitempty" parquet:"name=owning_service,type=BYTE_ARRAY,convertedtype=UTF8" json:"owning_service,omitempty" diff:"owning_service"`
	PrimaryRegion          string              `bson:"primary_region,omitempty" ion:"primary_region" dynamodbav:"primary_region,omitempty" parquet:"name=primary_region,type=BYTE_ARRAY,convertedtype=UTF8" json:"primary_region,omitempty" diff:"primary_region"`
	RotationEnabled        bool                `bson:"rotation_enabled,omitempty" ion:"rotation_enabled" dynamodbav:"rotation_enabled" parquet:"name=rotation_enabled,type=BOOLEAN" json:"rotation_enabled,omitempty" diff:"rotation_enabled"`
	RotationLambdaARN      string              `bson:"rotation_lambda_arn,omitempty" ion:"rotation_lambda_arn" dynamodbav:"rotation_lambda_arn,omitempty" parquet:"name=rotation_lambda_arn,type=BYTE_ARRAY,convertedtype=UTF8" json:"rotation_lambda_arn,omitempty" diff:"rotation_lambda_arn"`
	RotationRules          *RotationRulesType  `bson:"rotation_rules,omitempty" ion:"rotation_rules" dynamodbav:"rotation_rules,omitempty" parquet:"name=rotation_rules" json:"rotation_rules,omitempty" diff:"rotation_rules"`
	SecretVersionsToStages map[string][]string `bson:"secret_versions_to_stages,omitempty" ion:"secret_versions_to_stages" dynamodbav:"secret_versions_to_stages,omitempty" parquet:"name=secret_versions_to_stages,type=MAP,valuetype=BYTE_ARRAY,valueconvertedtype=UTF8" json:"secret_versions_to_stages,omitempty" diff:"secret_versions_to_stages"`
	Tags                   map[string]string   `bson:"tags,omitempty" ion:"tags" dynamodbav:"tags,omitempty" parquet:"name=tags,type=MAP,keytype=BYTE_ARRAY,valuetype=BYTE_ARRAY,keyconvertedtype=UTF8,valueconvertedtype=UTF8" json:"tags,omitempty" diff:"tags"`
	AccountId              string              `bson:"account_id,omitempty" ion:"account_id" dynamodbav:"account_id,omitempty" parquet:"name=account_id,type=BYTE_ARRAY,convertedtype=UTF8" json:"account_id,omitempty" diff:"account_id"`
	Region                 string              `bson:"region,omitempty" ion:"region" dynamodbav:"region,omitempty" parquet:"name=region,type=BYTE_ARRAY,convertedtype=UTF8" json:"region,omitempty" diff:"region"`
	ReportTime             int64               `bson:"report_time,omitempty" ion:"report_time" dynamodbav:"report_time,omitempty" parquet:"name=report_time,type=INT64,convertedtype=TIMESTAMP_MILLIS" json:"report_time,omitempty" diff:"report_time,immutable"`
	InventoryUUID          string              `bson:"_id,omitempty" ion:"_id" dynamodbav:"_id,omitempty" parquet:"name=inventory_uuid,type=BYTE_ARRAY,convertedtype=UTF8" json:"_id,omitempty" diff:"-"`
}
