//AUTOGENERATED CODE DO NOT EDIT
package mongo

import (
	"context"
	"github.com/sheacloud/cloud-inventory/internal/db"
	"github.com/sheacloud/cloud-inventory/pkg/aws/apigatewayv2"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"time"
)

type MongoApiGatewayV2DAO struct {
	db *mongo.Database
}

func (dao *MongoApiGatewayV2DAO) ListApis(ctx context.Context, reportTime time.Time, accountID, region *string, limit, offset *int64) ([]*apigatewayv2.Api, error) {
	filter := bson.D{
		bson.E{"report_time", reportTime},
	}
	if accountID != nil {
		filter = append(filter, bson.E{Key: "account_id", Value: *accountID})
	}
	if region != nil {
		filter = append(filter, bson.E{Key: "region", Value: *region})
	}

	var results []*apigatewayv2.Api
	cursor, err := dao.db.Collection("aws_apigatewayv2_apis").Find(ctx, filter)
	if err != nil {
		return nil, err
	}

	err = cursor.All(ctx, &results)
	if err != nil {
		return nil, err
	}

	return results, nil
}

func (dao *MongoApiGatewayV2DAO) GetApi(ctx context.Context, reportTime time.Time, id string) (*apigatewayv2.Api, error) {
	filter := bson.D{
		bson.E{"report_time", reportTime},
		bson.E{"api_id", id},
	}

	var result *apigatewayv2.Api
	err := dao.db.Collection("aws_apigatewayv2_apis").FindOne(ctx, filter).Decode(&result)

	return result, err
}

func (dao *MongoApiGatewayV2DAO) PutApis(ctx context.Context, resources []*apigatewayv2.Api) error {
	if len(resources) == 0 {
		return nil
	}
	writes := make([]interface{}, len(resources))
	for i, resource := range resources {
		writes[i] = resource
	}
	_, err := dao.db.Collection("aws.apigatewayv2.apis").InsertMany(ctx, writes)

	return err
}

func (dao *MongoApiGatewayV2DAO) GetApiReportTimes(ctx context.Context, reportDate time.Time) ([]string, error) {
	return DistinctReportTimes(ctx, dao.db.Collection("aws_apigatewayv2_apis"), reportDate)
}

func (dao *MongoApiGatewayV2DAO) GetReferencedApiReportTime(ctx context.Context, reportDate time.Time, timeSelection db.TimeSelection, timeReference time.Time) (*time.Time, error) {
	return GetReportTime(ctx, dao.db.Collection("aws_apigatewayv2_apis"), reportDate, timeSelection, timeReference)
}
