//AUTOGENERATED CODE DO NOT EDIT
package mongo

import (
	"context"
	"github.com/sheacloud/cloud-inventory/internal/db"
	"github.com/sheacloud/cloud-inventory/pkg/aws/redshift"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"time"
)

type MongoRedshiftDAO struct {
	db *mongo.Database
}

func (dao *MongoRedshiftDAO) ListClusters(ctx context.Context, reportTime time.Time, accountID, region *string, limit, offset *int64) ([]*redshift.Cluster, error) {
	filter := bson.D{
		bson.E{"report_time", reportTime},
	}
	if accountID != nil {
		filter = append(filter, bson.E{Key: "account_id", Value: *accountID})
	}
	if region != nil {
		filter = append(filter, bson.E{Key: "region", Value: *region})
	}

	var results []*redshift.Cluster
	cursor, err := dao.db.Collection("aws_redshift_clusters").Find(ctx, filter)
	if err != nil {
		return nil, err
	}

	err = cursor.All(ctx, &results)
	if err != nil {
		return nil, err
	}

	return results, nil
}

func (dao *MongoRedshiftDAO) GetCluster(ctx context.Context, reportTime time.Time, id string) (*redshift.Cluster, error) {
	filter := bson.D{
		bson.E{"report_time", reportTime},
		bson.E{"cluster_identifier", id},
	}

	var result *redshift.Cluster
	err := dao.db.Collection("aws_redshift_clusters").FindOne(ctx, filter).Decode(&result)

	return result, err
}

func (dao *MongoRedshiftDAO) PutClusters(ctx context.Context, resources []*redshift.Cluster) error {
	if len(resources) == 0 {
		return nil
	}
	writes := make([]interface{}, len(resources))
	for i, resource := range resources {
		writes[i] = resource
	}
	_, err := dao.db.Collection("aws.redshift.clusters").InsertMany(ctx, writes)

	return err
}

func (dao *MongoRedshiftDAO) GetClusterReportTimes(ctx context.Context, reportDate time.Time) ([]string, error) {
	return DistinctReportTimes(ctx, dao.db.Collection("aws_redshift_clusters"), reportDate)
}

func (dao *MongoRedshiftDAO) GetReferencedClusterReportTime(ctx context.Context, reportDate time.Time, timeSelection db.TimeSelection, timeReference time.Time) (*time.Time, error) {
	return GetReportTime(ctx, dao.db.Collection("aws_redshift_clusters"), reportDate, timeSelection, timeReference)
}
