//AUTOGENERATED CODE DO NOT EDIT
package mongo

import (
	"context"
	"github.com/sheacloud/cloud-inventory/internal/db"
	"github.com/sheacloud/cloud-inventory/pkg/aws/dynamodb"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"time"
)

type MongoDynamoDBDAO struct {
	db *mongo.Database
}

func (dao *MongoDynamoDBDAO) ListTables(ctx context.Context, reportTime time.Time, accountID, region *string, limit, offset *int64) ([]*dynamodb.Table, error) {
	filter := bson.D{
		bson.E{"report_time", reportTime},
	}
	if accountID != nil {
		filter = append(filter, bson.E{Key: "account_id", Value: *accountID})
	}
	if region != nil {
		filter = append(filter, bson.E{Key: "region", Value: *region})
	}

	var results []*dynamodb.Table
	cursor, err := dao.db.Collection("aws_dynamodb_tables").Find(ctx, filter)
	if err != nil {
		return nil, err
	}

	err = cursor.All(ctx, &results)
	if err != nil {
		return nil, err
	}

	return results, nil
}

func (dao *MongoDynamoDBDAO) GetTable(ctx context.Context, reportTime time.Time, id string) (*dynamodb.Table, error) {
	filter := bson.D{
		bson.E{"report_time", reportTime},
		bson.E{"table_arn", id},
	}

	var result *dynamodb.Table
	err := dao.db.Collection("aws_dynamodb_tables").FindOne(ctx, filter).Decode(&result)

	return result, err
}

func (dao *MongoDynamoDBDAO) PutTables(ctx context.Context, resources []*dynamodb.Table) error {
	if len(resources) == 0 {
		return nil
	}
	writes := make([]interface{}, len(resources))
	for i, resource := range resources {
		writes[i] = resource
	}
	_, err := dao.db.Collection("aws.dynamodb.tables").InsertMany(ctx, writes)

	return err
}

func (dao *MongoDynamoDBDAO) GetTableReportTimes(ctx context.Context, reportDate time.Time) ([]string, error) {
	return DistinctReportTimes(ctx, dao.db.Collection("aws_dynamodb_tables"), reportDate)
}

func (dao *MongoDynamoDBDAO) GetReferencedTableReportTime(ctx context.Context, reportDate time.Time, timeSelection db.TimeSelection, timeReference time.Time) (*time.Time, error) {
	return GetReportTime(ctx, dao.db.Collection("aws_dynamodb_tables"), reportDate, timeSelection, timeReference)
}
