//AUTOGENERATED CODE DO NOT EDIT
package mongo

import (
	"context"
	"github.com/sheacloud/cloud-inventory/internal/db"
	"github.com/sheacloud/cloud-inventory/pkg/aws/lambda"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"time"
)

type MongoLambdaDAO struct {
	db *mongo.Database
}

func (dao *MongoLambdaDAO) ListFunctions(ctx context.Context, reportTime time.Time, accountID, region *string, limit, offset *int64) ([]*lambda.Function, error) {
	filter := bson.D{
		bson.E{"report_time", reportTime},
	}
	if accountID != nil {
		filter = append(filter, bson.E{Key: "account_id", Value: *accountID})
	}
	if region != nil {
		filter = append(filter, bson.E{Key: "region", Value: *region})
	}

	var results []*lambda.Function
	cursor, err := dao.db.Collection("aws_lambda_functions").Find(ctx, filter)
	if err != nil {
		return nil, err
	}

	err = cursor.All(ctx, &results)
	if err != nil {
		return nil, err
	}

	return results, nil
}

func (dao *MongoLambdaDAO) GetFunction(ctx context.Context, reportTime time.Time, id string) (*lambda.Function, error) {
	filter := bson.D{
		bson.E{"report_time", reportTime},
		bson.E{"function_arn", id},
	}

	var result *lambda.Function
	err := dao.db.Collection("aws_lambda_functions").FindOne(ctx, filter).Decode(&result)

	return result, err
}

func (dao *MongoLambdaDAO) PutFunctions(ctx context.Context, resources []*lambda.Function) error {
	if len(resources) == 0 {
		return nil
	}
	writes := make([]interface{}, len(resources))
	for i, resource := range resources {
		writes[i] = resource
	}
	_, err := dao.db.Collection("aws.lambda.functions").InsertMany(ctx, writes)

	return err
}

func (dao *MongoLambdaDAO) GetFunctionReportTimes(ctx context.Context, reportDate time.Time) ([]string, error) {
	return DistinctReportTimes(ctx, dao.db.Collection("aws_lambda_functions"), reportDate)
}

func (dao *MongoLambdaDAO) GetReferencedFunctionReportTime(ctx context.Context, reportDate time.Time, timeSelection db.TimeSelection, timeReference time.Time) (*time.Time, error) {
	return GetReportTime(ctx, dao.db.Collection("aws_lambda_functions"), reportDate, timeSelection, timeReference)
}
