//AUTOGENERATED CODE DO NOT EDIT
// This file is automatically generated from /internal/codegen/templates/aws_client_interface_file.tmpl
package aws

import (
	"github.com/sheacloud/cloud-inventory/pkg/aws/interfaces"
)

type AwsClientInterface interface {
	ApiGateway() interfaces.ApiGatewayClient
	ApiGatewayV2() interfaces.ApiGatewayV2Client
	Backup() interfaces.BackupClient
	CloudTrail() interfaces.CloudTrailClient
	CloudWatchLogs() interfaces.CloudWatchLogsClient
	DynamoDB() interfaces.DynamoDBClient
	EC2() interfaces.EC2Client
	ECS() interfaces.ECSClient
	EFS() interfaces.EFSClient
	ElastiCache() interfaces.ElastiCacheClient
	ElasticLoadBalancing() interfaces.ElasticLoadBalancingClient
	ElasticLoadBalancingV2() interfaces.ElasticLoadBalancingV2Client
	IAM() interfaces.IAMClient
	Lambda() interfaces.LambdaClient
	RDS() interfaces.RDSClient
	Redshift() interfaces.RedshiftClient
	Route53() interfaces.Route53Client
	S3() interfaces.S3Client
	SNS() interfaces.SNSClient
	SQS() interfaces.SQSClient
	StorageGateway() interfaces.StorageGatewayClient
}
