//AUTOGENERATED CODE DO NOT EDIT
package ecs



type Cluster struct {
	ActiveServicesCount int32 `parquet:"name=active_services_count,type=INT32"`
	Attachments []*Attachment `parquet:"name=attachments,type=MAP,convertedtype=LIST"`
	AttachmentsStatus string `parquet:"name=attachments_status,type=BYTE_ARRAY,convertedtype=UTF8"`
	CapacityProviders []string `parquet:"name=capacity_providers,type=MAP,convertedtype=LIST,valuetype=BYTE_ARRAY,valueconvertedtype=UTF8"`
	ClusterArn string `parquet:"name=cluster_arn,type=BYTE_ARRAY,convertedtype=UTF8" inventory_primary_key:"true"`
	ClusterName string `parquet:"name=cluster_name,type=BYTE_ARRAY,convertedtype=UTF8"`
	Configuration *ClusterConfiguration `parquet:"name=configuration"`
	DefaultCapacityProviderStrategy []*CapacityProviderStrategyItem `parquet:"name=default_capacity_provider_strategy,type=MAP,convertedtype=LIST"`
	PendingTasksCount int32 `parquet:"name=pending_tasks_count,type=INT32"`
	RegisteredContainerInstancesCount int32 `parquet:"name=registered_container_instances_count,type=INT32"`
	RunningTasksCount int32 `parquet:"name=running_tasks_count,type=INT32"`
	Settings []*ClusterSetting `parquet:"name=settings,type=MAP,convertedtype=LIST"`
	Statistics []*KeyValuePair `parquet:"name=statistics,type=MAP,convertedtype=LIST"`
	Status string `parquet:"name=status,type=BYTE_ARRAY,convertedtype=UTF8"`
	TagsOld []*Tag `parquet:"name=tags_old,type=MAP,convertedtype=LIST"`
	AccountId string `parquet:"name=account_id,type=BYTE_ARRAY,convertedtype=UTF8"`
	Region string `parquet:"name=region,type=BYTE_ARRAY,convertedtype=UTF8"`
	ReportTime int64 `parquet:"name=report_time,type=INT64,convertedtype=TIMESTAMP_MILLIS"`
	Tags map[string]string `parquet:"name=tags,type=MAP,keytype=BYTE_ARRAY,valuetype=BYTE_ARRAY,keyconvertedtype=UTF8,valueconvertedtype=UTF8"`
}

