//AUTOGENERATED CODE DO NOT EDIT
package dynamodb

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	dynamo "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/sheacloud/cloud-inventory/internal/db"
	"github.com/sheacloud/cloud-inventory/pkg/aws/elasticloadbalancingv2"
	"time"
)

type DynamoDBElasticLoadBalancingV2DAO struct {
	client     *dynamo.Client
	maxRetries int
}

func (dao *DynamoDBElasticLoadBalancingV2DAO) ListLoadBalancers(ctx context.Context, reportTime time.Time, accountID, region *string, limit, offset *int64) ([]*elasticloadbalancingv2.LoadBalancer, error) {
	tableName := "cloud-inventory-aws-elasticloadbalancingv2-load-balancers"
	items, _, err := ListItems(ctx, dao.client, tableName, reportTime, "load_balancer_arn", nil)
	if err != nil {
		return nil, err
	}
	var resources []*elasticloadbalancingv2.LoadBalancer
	err = attributevalue.UnmarshalListOfMaps(items, &resources)
	if err != nil {
		return nil, err
	}
	return resources, nil
}

func (dao *DynamoDBElasticLoadBalancingV2DAO) GetLoadBalancer(ctx context.Context, reportTime time.Time, id string) (*elasticloadbalancingv2.LoadBalancer, error) {
	tableName := "cloud-inventory-aws-elasticloadbalancingv2-load-balancers"
	item, err := GetItem(ctx, dao.client, tableName, reportTime, id, "load_balancer_arn")
	if err != nil {
		return nil, err
	}
	var resource *elasticloadbalancingv2.LoadBalancer
	err = attributevalue.UnmarshalMap(item, &resource)
	if err != nil {
		return nil, err
	}
	return resource, nil
}

func (dao *DynamoDBElasticLoadBalancingV2DAO) PutLoadBalancers(ctx context.Context, resources []*elasticloadbalancingv2.LoadBalancer) error {
	items := make([]map[string]types.AttributeValue, len(resources))
	for i, resource := range resources {
		item, err := attributevalue.MarshalMap(resource)
		if err != nil {
			return err
		}
		items[i] = item
	}
	return BatchWriteItems(ctx, dao.client, dao.maxRetries, "cloud-inventory-aws-elasticloadbalancingv2-load-balancers", items)
}

func (dao *DynamoDBElasticLoadBalancingV2DAO) GetLoadBalancerReportTimes(ctx context.Context, reportDate time.Time) ([]string, error) {
	return DistinctReportTimes(ctx, dao.client, reportDate, "aws", "elasticloadbalancingv2", "load_balancers")
}

func (dao *DynamoDBElasticLoadBalancingV2DAO) GetReferencedLoadBalancerReportTime(ctx context.Context, reportDate time.Time, timeSelection db.TimeSelection, timeReference time.Time) (*time.Time, error) {
	return GetReportTime(ctx, dao.client, reportDate, timeSelection, timeReference, "aws", "elasticloadbalancingv2", "load_balancers")
}

func (dao *DynamoDBElasticLoadBalancingV2DAO) ListTargetGroups(ctx context.Context, reportTime time.Time, accountID, region *string, limit, offset *int64) ([]*elasticloadbalancingv2.TargetGroup, error) {
	tableName := "cloud-inventory-aws-elasticloadbalancingv2-target-groups"
	items, _, err := ListItems(ctx, dao.client, tableName, reportTime, "target_group_arn", nil)
	if err != nil {
		return nil, err
	}
	var resources []*elasticloadbalancingv2.TargetGroup
	err = attributevalue.UnmarshalListOfMaps(items, &resources)
	if err != nil {
		return nil, err
	}
	return resources, nil
}

func (dao *DynamoDBElasticLoadBalancingV2DAO) GetTargetGroup(ctx context.Context, reportTime time.Time, id string) (*elasticloadbalancingv2.TargetGroup, error) {
	tableName := "cloud-inventory-aws-elasticloadbalancingv2-target-groups"
	item, err := GetItem(ctx, dao.client, tableName, reportTime, id, "target_group_arn")
	if err != nil {
		return nil, err
	}
	var resource *elasticloadbalancingv2.TargetGroup
	err = attributevalue.UnmarshalMap(item, &resource)
	if err != nil {
		return nil, err
	}
	return resource, nil
}

func (dao *DynamoDBElasticLoadBalancingV2DAO) PutTargetGroups(ctx context.Context, resources []*elasticloadbalancingv2.TargetGroup) error {
	items := make([]map[string]types.AttributeValue, len(resources))
	for i, resource := range resources {
		item, err := attributevalue.MarshalMap(resource)
		if err != nil {
			return err
		}
		items[i] = item
	}
	return BatchWriteItems(ctx, dao.client, dao.maxRetries, "cloud-inventory-aws-elasticloadbalancingv2-target-groups", items)
}

func (dao *DynamoDBElasticLoadBalancingV2DAO) GetTargetGroupReportTimes(ctx context.Context, reportDate time.Time) ([]string, error) {
	return DistinctReportTimes(ctx, dao.client, reportDate, "aws", "elasticloadbalancingv2", "target_groups")
}

func (dao *DynamoDBElasticLoadBalancingV2DAO) GetReferencedTargetGroupReportTime(ctx context.Context, reportDate time.Time, timeSelection db.TimeSelection, timeReference time.Time) (*time.Time, error) {
	return GetReportTime(ctx, dao.client, reportDate, timeSelection, timeReference, "aws", "elasticloadbalancingv2", "target_groups")
}
