//AUTOGENERATED CODE DO NOT EDIT
package dynamodb

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	dynamo "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/sheacloud/cloud-inventory/internal/db"
	"github.com/sheacloud/cloud-inventory/pkg/aws/elasticloadbalancing"
	"time"
)

type DynamoDBElasticLoadBalancingDAO struct {
	client     *dynamo.Client
	maxRetries int
}

func (dao *DynamoDBElasticLoadBalancingDAO) ListLoadBalancers(ctx context.Context, reportTime time.Time, accountID, region *string, limit, offset *int64) ([]*elasticloadbalancing.LoadBalancer, error) {
	tableName := "cloud-inventory-aws-elasticloadbalancing-load-balancers"
	items, _, err := ListItems(ctx, dao.client, tableName, reportTime, "load_balancer_name", nil)
	if err != nil {
		return nil, err
	}
	var resources []*elasticloadbalancing.LoadBalancer
	err = attributevalue.UnmarshalListOfMaps(items, &resources)
	if err != nil {
		return nil, err
	}
	return resources, nil
}

func (dao *DynamoDBElasticLoadBalancingDAO) GetLoadBalancer(ctx context.Context, reportTime time.Time, id string) (*elasticloadbalancing.LoadBalancer, error) {
	tableName := "cloud-inventory-aws-elasticloadbalancing-load-balancers"
	item, err := GetItem(ctx, dao.client, tableName, reportTime, id, "load_balancer_name")
	if err != nil {
		return nil, err
	}
	var resource *elasticloadbalancing.LoadBalancer
	err = attributevalue.UnmarshalMap(item, &resource)
	if err != nil {
		return nil, err
	}
	return resource, nil
}

func (dao *DynamoDBElasticLoadBalancingDAO) PutLoadBalancers(ctx context.Context, resources []*elasticloadbalancing.LoadBalancer) error {
	items := make([]map[string]types.AttributeValue, len(resources))
	for i, resource := range resources {
		item, err := attributevalue.MarshalMap(resource)
		if err != nil {
			return err
		}
		items[i] = item
	}
	return BatchWriteItems(ctx, dao.client, dao.maxRetries, "cloud-inventory-aws-elasticloadbalancing-load-balancers", items)
}

func (dao *DynamoDBElasticLoadBalancingDAO) GetLoadBalancerReportTimes(ctx context.Context, reportDate time.Time) ([]string, error) {
	return DistinctReportTimes(ctx, dao.client, reportDate, "aws", "elasticloadbalancing", "load_balancers")
}

func (dao *DynamoDBElasticLoadBalancingDAO) GetReferencedLoadBalancerReportTime(ctx context.Context, reportDate time.Time, timeSelection db.TimeSelection, timeReference time.Time) (*time.Time, error) {
	return GetReportTime(ctx, dao.client, reportDate, timeSelection, timeReference, "aws", "elasticloadbalancing", "load_balancers")
}
