//AUTOGENERATED CODE DO NOT EDIT
package dynamodb

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	dynamo "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/sheacloud/cloud-inventory/internal/db"
	"github.com/sheacloud/cloud-inventory/pkg/aws/redshift"
	"time"
)

type DynamoDBRedshiftDAO struct {
	client     *dynamo.Client
	maxRetries int
}

func (dao *DynamoDBRedshiftDAO) ListClusters(ctx context.Context, reportTime time.Time, accountID, region *string, limit, offset *int64) ([]*redshift.Cluster, error) {
	tableName := "cloud-inventory-aws-redshift-clusters"
	items, _, err := ListItems(ctx, dao.client, tableName, reportTime, "cluster_identifier", nil)
	if err != nil {
		return nil, err
	}
	var resources []*redshift.Cluster
	err = attributevalue.UnmarshalListOfMaps(items, &resources)
	if err != nil {
		return nil, err
	}
	return resources, nil
}

func (dao *DynamoDBRedshiftDAO) GetCluster(ctx context.Context, reportTime time.Time, id string) (*redshift.Cluster, error) {
	tableName := "cloud-inventory-aws-redshift-clusters"
	item, err := GetItem(ctx, dao.client, tableName, reportTime, id, "cluster_identifier")
	if err != nil {
		return nil, err
	}
	var resource *redshift.Cluster
	err = attributevalue.UnmarshalMap(item, &resource)
	if err != nil {
		return nil, err
	}
	return resource, nil
}

func (dao *DynamoDBRedshiftDAO) PutClusters(ctx context.Context, resources []*redshift.Cluster) error {
	items := make([]map[string]types.AttributeValue, len(resources))
	for i, resource := range resources {
		item, err := attributevalue.MarshalMap(resource)
		if err != nil {
			return err
		}
		items[i] = item
	}
	return BatchWriteItems(ctx, dao.client, dao.maxRetries, "cloud-inventory-aws-redshift-clusters", items)
}

func (dao *DynamoDBRedshiftDAO) GetClusterReportTimes(ctx context.Context, reportDate time.Time) ([]string, error) {
	return DistinctReportTimes(ctx, dao.client, reportDate, "aws", "redshift", "clusters")
}

func (dao *DynamoDBRedshiftDAO) GetReferencedClusterReportTime(ctx context.Context, reportDate time.Time, timeSelection db.TimeSelection, timeReference time.Time) (*time.Time, error) {
	return GetReportTime(ctx, dao.client, reportDate, timeSelection, timeReference, "aws", "redshift", "clusters")
}
