//AUTOGENERATED CODE DO NOT EDIT
// This file is automatically generated from /internal/codegen/templates/aws_referenced_resource_file.tmpl
package ssm

type ParameterInlinePolicy struct {
	PolicyStatus string `bson:"policy_status,omitempty" ion:"policy_status" dynamodbav:"policy_status,omitempty" parquet:"name=policy_status,type=BYTE_ARRAY,convertedtype=UTF8" json:"policy_status,omitempty" diff:"policy_status"`
	PolicyText   string `bson:"policy_text,omitempty" ion:"policy_text" dynamodbav:"policy_text,omitempty" parquet:"name=policy_text,type=BYTE_ARRAY,convertedtype=UTF8" json:"policy_text,omitempty" diff:"policy_text"`
	PolicyType   string `bson:"policy_type,omitempty" ion:"policy_type" dynamodbav:"policy_type,omitempty" parquet:"name=policy_type,type=BYTE_ARRAY,convertedtype=UTF8" json:"policy_type,omitempty" diff:"policy_type"`
}
